import '@/src/style/globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Navbar from '@/src/components/navbar'
import { ReactNode } from 'react'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

const RootLayout = (props: RootLayoutProps) => {
  const { children } = props
  return (
    <html lang="en" className={'dark'}>
      <body className={roboto.className} style={roboto.style}>
        <Navbar />
        <main className={'font-sans'}>{children}</main>
      </body>
    </html>
  )
}
export default RootLayout